apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-drtukwzs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-drtukwzs:a6bcab513847bd7537756814e38831563064491d@sha256:53114e0236137a499eae8cf48e767c4c00e9f10aac83ce72f614a40c5a95ee42
          name: container-image
